package org.waterwood.consts;

public enum ColorCode {
    BLACK,DARKBLUE,DARK_GREEN,DARK_AQUA,DARK_RED,DARK_PURPLE,GOLD,GRAY,
    DARK_GRAY,BLUE,GREEN,AQUA,RED,LIGHT_PURPLE,YELLOW,WHITE,RESET,
    RAINBOW
}
